version: '3.7'
services:
  master:
    image: locust-performance:2.5.1
    ports:
      - "8089:8089"
    build:
      context: .
      # path to Dockerfile is relative to the context path set above
      dockerfile: DockerFile
    working_dir: /home/locust
    command: -f locust-files/test.py --master -H http://master:8089

  worker:
    image: locust-performance:2.5.1
    build:
      context: .
      # path to Dockerfile is relative to the context path set above
      dockerfile: DockerFile
    working_dir: /home/locust
    command: -f locust-files/test.py --worker --master-host master
